# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sample.proto", :syntax => :proto3) do
    add_message "sample.UploadRequest" do
      optional :file_blob, :bytes, 1
      optional :file_name, :string, 2
    end
    add_message "sample.UploadResponse" do
      optional :created_at, :message, 1, "google.protobuf.Timestamp"
      optional :error, :enum, 3, "sample.ErrorType"
    end
    add_message "sample.DownloadRequest" do
      optional :file_name, :string, 1
    end
    add_message "sample.DownloadResponse" do
      optional :file_blob, :bytes, 1
      optional :error, :enum, 3, "sample.ErrorType"
    end
    add_enum "sample.ErrorType" do
      value :NO_ERROR, 0
      value :UNKNOWN_ERROR, 1
      value :VALIDATION_ERROR, 2
    end
  end
end

module Sample
  UploadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.UploadRequest").msgclass
  UploadResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.UploadResponse").msgclass
  DownloadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.DownloadRequest").msgclass
  DownloadResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.DownloadResponse").msgclass
  ErrorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.ErrorType").enummodule
end
