# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sample.proto for package 'sample'
# Original file comments:
# バージョン定義
# 基本的に "proto3" を指定

require 'grpc'
require_relative 'sample_pb'

module Sample
  module FileStorage
    # サービスとサービスが持つメソッドを定義
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sample.FileStorage'

      # ファイルのアップロード用メソッド
      # ファイル名・ファイルの中身を送る => ファイルを保存した日時・エラーを返す。
      rpc :Upload, ::Sample::UploadRequest, ::Sample::UploadResponse
      # ファイルのダウンロード用メソッド
      # ファイルのIDを送る => ファイルのバイナリ・拡張子・エラーを返す。
      rpc :Download, ::Sample::DownloadRequest, ::Sample::DownloadResponse
    end

    Stub = Service.rpc_stub_class
  end
  # 書き方
  # rpc メソッド名 (マイクロサービスに送るメッセージの型) returns (マイクロサービスが返すメッセージの型)
end
